site_name: Jaxtree Extensions
site_description: The documentation for the jaxtree-extensions python library.
site_author: Paul Gekeler
site_url: https://paulgekeler.github.io/jaxtree_extensions/

repo_name: paulgekeler/jaxtree_extensions
repo_url: https://github.com/paulgekeler/jaxtree_extensions

strict: true

extra_css:
  - _assets/custom_css.css

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github  

  features:
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - header.autohide

plugins:
  - search
  - hippogriffe:
      extra_public_objects:
        - numpy.dtype
        - equinox.if_array
        - jax.ShapeDtypeStruct
        - jax.extend.core.ClosedJaxpr
        - jax.Device
        - jax.sharding.Sharding
  - mkdocstrings:
      handlers:
        python:
          paths: [.] # Allow mkdocstrings to find the neojax package
          options:
            docstring_style: google
            docstring_options:
              returns_multiple_items: false # Treat multiple return values as one
            force_inspection: true
            heading_level: 4
            inherited_members: false
            members_order: source
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            filters:
              - "!^_[^_]"  # Hides protected attrs/methods (e.g., _local_var)
              - "!^__[^c]" # Blocks all dunder attrs

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: ["."]
  - toc:
      permalink: "¤"
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - API Reference:
      - Pruning: api/prune.md
      - Path Selection: api/path_select.md
      - Mismatched Zip: api/zip_mismatched.md
      - Map Enumerate: api/enumerate.md
      - Comparison: api/compare.md
      - Path Reduction: api/reduce_path.md